
GUI
package myPackage;
import java.awt.Component;
import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.StringReader;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
//import jxta Library
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import net.jxta.document.MimeMediaType;
import net.jxta.document.StructuredDocumentFactory;
import net.jxta.peergroup.PeerGroupID;
import net.jxta.share.ContentAdvertisement;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.html.HTMLDocument;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
//this is Main Frame and it handles the Application start up and also initialisation of all
//object that are needed in out program
public class frmMain extends javax.swing.JFrame
{
//Defining Class Variables
private final ImageIcon mp3Icon = new ImageIcon(getClass().getResource("/myPackage/myIcons/16x16/
mp3Icon.png"));
private final ImageIcon VideoIcon = new ImageIcon(getClass().getResource("/myPackage/myIcons/16x16/
videoIcon.png"));
private final ImageIcon OthersIcon = new ImageIcon(getClass().getResource("/myPackage/myIcons/16x16/
otherfilesIcon.png"));
static String Path = null;
//Original check sum which will be taken from Content Advertisement
//to make sure download is not corrupted
static String OriginalCheckSum = "unknown";
static String myFileName=null;
static String html1="";
//Classes that needed to launch into jxta, share contenets through JXTA network,
//Search for content, Download content, Chat services and Peers Listing in Group
static StartJXTA connection = null;
public static ChatInput chatIn = null;
public static ChatOutput chatOut=null;
static PeersListing peersList = null;
static Sharing launchSharing =null;
static SearchFile startSearch =null;
static DownloadFile download = null;
static CheckSumCalc myCheckSum = new CheckSumCalc();
static ContentAdvertisement [] contentAdv = null;
private String RelevanceFactor="20";
public frmMain() //Main Frame Constructor
{
initComponents();
}
/** This method is called from within the constructor to
* initialize the form.
* WARNING: Do NOT modify this code. The content of this method is
* always regenerated by the Form Editor.
*/
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {
jTabbedPane1 = new javax.swing.JTabbedPane();
jPanel1 = new javax.swing.JPanel();
jScrollPane1 = new javax.swing.JScrollPane();
txtLog = new javax.swing.JTextArea();
jPanel2 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
txtFilename = new javax.swing.JTextField();
jScrollPane2 = new javax.swing.JScrollPane();
mySearchTable = new javax.swing.JTable();
jSeparator3 = new javax.swing.JSeparator();
btnSearch = new javax.swing.JButton();
btnStop = new javax.swing.JButton();
btnDownload = new javax.swing.JButton();
jSlider1 = new javax.swing.JSlider();
jLabel6 = new javax.swing.JLabel();
jPanel3 = new javax.swing.JPanel();
jScrollPane3 = new javax.swing.JScrollPane();
mySharedTable = new javax.swing.JTable();
jSeparator4 = new javax.swing.JSeparator();
btnReload = new javax.swing.JButton();
jPanel4 = new javax.swing.JPanel();
jLabel2 = new javax.swing.JLabel();
jLabel3 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
lblFilename = new javax.swing.JLabel();
lblStatus = new javax.swing.JLabel();
myProgressBar = new javax.swing.JProgressBar();
btnVerify = new javax.swing.JButton();
btnCancel = new javax.swing.JButton();
jPanel5 = new javax.swing.JPanel();
jScrollPane4 = new javax.swing.JScrollPane();
txtChatArea = new javax.swing.JTextArea();
jSeparator5 = new javax.swing.JSeparator();
jLabel5 = new javax.swing.JLabel();
txtMessage = new javax.swing.JTextField();
btnSendMessage = new javax.swing.JButton();
jPanel6 = new javax.swing.JPanel();
jScrollPane5 = new javax.swing.JScrollPane();
ListOfPeers = new javax.swing.JList();
btnFindPeers = new javax.swing.JButton();
btnStopPeerSearch = new javax.swing.JButton();
jPanel8 = new javax.swing.JPanel();
jScrollPane8 = new javax.swing.JScrollPane();
jTable1 = new javax.swing.JTable();
InternalTaggingbtn = new javax.swing.JButton();
jPanel7 = new javax.swing.JPanel();
jScrollPane11 = new javax.swing.JScrollPane();
InternalTag = new javax.swing.JEditorPane();
InternalTaggingUpdate = new javax.swing.JButton();
InternalText = new javax.swing.JTextField();
InternalTagsCombo = new javax.swing.JComboBox();
InternalVisualize = new javax.swing.JButton();
InternalFont = new javax.swing.JComboBox();
InternalChange = new javax.swing.JButton();
jPanel9 = new javax.swing.JPanel();
jScrollPane9 = new javax.swing.JScrollPane();
jTable2 = new javax.swing.JTable();
ExternalTaggingbtn = new javax.swing.JButton();
jPanel10 = new javax.swing.JPanel();
jScrollPane7 = new javax.swing.JScrollPane();
ExternalTag = new javax.swing.JEditorPane();
ExternalTaggingUpdate = new javax.swing.JButton();
ExternalText = new javax.swing.JTextField();
ExternalTagsCombo = new javax.swing.JComboBox();
ExternalFont = new javax.swing.JComboBox();
ExternalChange = new javax.swing.JButton();
ExternalVisualize = new javax.swing.JButton();
jMenuBar1 = new javax.swing.JMenuBar();
jMenu1 = new javax.swing.JMenu();
MenuItemConnect = new javax.swing.JMenuItem();
MenuItemDisconnect = new javax.swing.JMenuItem();
jSeparator1 = new javax.swing.JSeparator();
MenuItemExit = new javax.swing.JMenuItem();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setLocationByPlatform(true);
jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection Information:"));
txtLog.setColumns(20);
txtLog.setEditable(false);
txtLog.setRows(5);
txtLog.setText("Application starting.................................................................\n");
txtLog.setToolTipText("Connection Information");
txtLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log:"));
jScrollPane1.setViewportView(txtLog);
javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
.addContainerGap())
);
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
.addContainerGap())
);
jTabbedPane1.addTab("Connection Log", new javax.swing.ImageIcon(getClass().getResource("/myPackage/
myIcons/24x24/LogIcon.png")), jPanel1, "Connection Information"); // NOI18N
jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search for Files:"));
jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
jLabel1.setText("File Name:");
txtFilename.setToolTipText("Enter File Name to search for.");
mySearchTable.setAutoCreateRowSorter(true);
mySearchTable.setModel(new javax.swing.table.DefaultTableModel(
new Object [][] {
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null},
{null, null, null}
},
new String [] {
"File Name", "Size Bytes", "Check Sum (CRC-32)"
}
));
mySearchTable.setToolTipText("List of Found Files.");
jScrollPane2.setViewportView(mySearchTable);
btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/myIcons/24x24/
searchIcon.png"))); // NOI18N
btnSearch.setText("Search");
btnSearch.setToolTipText("Start Searching");
btnSearch.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnSearchActionPerformed(evt);
}
});
btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/myIcons/24x24/cancelIcon.png"))
); // NOI18N
btnStop.setText("Stop");
btnStop.setToolTipText("Stop searching progress");
btnStop.setEnabled(false);
btnStop.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnStopActionPerformed(evt);
}
});
btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/myIcons/24x24/
saveIcon.png"))); // NOI18N
btnDownload.setText("Download");
btnDownload.setToolTipText("Downloading Selected File.");
btnDownload.setEnabled(false);
btnDownload.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnDownloadActionPerformed(evt);
}
});
jSlider1.setMaximum(1000);
jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
public void stateChanged(javax.swing.event.ChangeEvent evt) {
jSlider1StateChanged(evt);
}
});
jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
jLabel6.setText("Relevance Factor:");
javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
.addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
794, Short.MAX_VALUE)
.addGroup(jPanel2Layout.createSequentialGroup()
.addComponent(jLabel1)
.addGap(38, 38, 38)
}}
